# Generated by Django 5.2.14 on 2026-05-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_faceimage_pose_userembedding_pose"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="cultivation",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
