# Generated by Codex on 2026-05-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_usermodel_cultivation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="email",
        ),
    ]
